### ISSUE TITLE
Feature Request: Support for Federation

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go-ansible#118]
The current role does not support configuring a federated group of Sensu Go clusters. A pending guide for this can be found here: https://github.com/sensu/sensu-docs/pull/1959

And the federation API is documented here: https://docs.sensu.io/sensu-go/5.15/api/federation/

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go-ansible/issues/190 

We'll need support for self-signed certificates to make federation support practical for most users.

**Comment by tadeboro** [comment]
Implemented in #258 and #259 .
