### ISSUE TITLE
Feature Request: Support api-keys  instead of user/pass

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go-ansible#149]
Sensu Go 5.15  now supports grant/revoke long lived api-keys, which are meant to provide programmatic access.

Reference:
https://docs.sensu.io/sensu-go/latest/guides/use-apikey-feature/

It would be great if auth object could be extended to include api-key attribute.
If api-key attribute exists, login via the /auth endpoint is no longer required and the request could be made with the api-key http header.

**Comment by tadeboro** [comment]
Fixed by #154
