### ISSUE TITLE
Initialize backend fails in check mode

### ISSUE THREAD

**Issue by Gillingham** [sensu/sensu-go-ansible#170]
**Bug description**
When running through the backend playbook in ansible checkmode Initialize backend fails because `init_command_test` is undefined.

**How to reproduce the bug**
1. Run the command `ansible-playbook -i inv ... -C`.

**Expected result**
This step should just skip like the `Check for sensu-backend init command` does

**Actual result**
Ansible exits prematurely
```
FAILED! => {"msg": "The conditional check 'init_command_test.rc == 0' failed. The error was: error while evaluating conditional (init_command_test.rc == 0): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '.../collections/ansible_collections/sensu/sensu_go/roles/backend/tasks/main.yml': line 80, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Initialize backend\n  ^ here\n"}
```

**Component versions**
- Python Version: 3.6.9
 - Ansible Version: 2.9.6
 - Sensu Go Collection Version: 1.3.0

**Comment by tadeboro** [comment]
Thanks, @Gillingham, for your report. We did manage to replicate the issue and will provide a fix for it ASAP.
