### ISSUE TITLE
Option to disable install role

### ISSUE THREAD

**Issue by Gillingham** [sensu/sensu-go-ansible#174]
On some of my deployments we're using the open source versions of sensu, either built and manually installed or compiled packages and installed from private repos. It would be nice to use these same playbooks on those systems as we do on systems using the official sensu repos and packages.

Maybe add a `no_sensu_install` or some other variable that can be defined when calling the `backend` or `agent` roles that then skips the calls to the `install` role.

**Comment by tadeboro** [comment]
You can specify which parts of the role you want to include using the `tasks_from` keyword. For example, https://github.com/sensu/sensu-go-ansible/blob/7309c1259b7d5b2aff15bdbf52a84d5c5ee9d625/tests/integration/molecule/role_agent_config/converge.yml#L8 shows how we only include the configuration part of the role in our integration tests.
