### ISSUE TITLE
Non-admin user can't authenticate themselves with API key

### ISSUE THREAD

**Issue by kafeinnet** [sensu/sensu-go-ansible#191]
Hi,

I want to use API key authentication for a non admin user so I created a role bound to a user allowing creation, listing and deletion of entities. I validated the API key with curl requests and the Authorization header. The backend and the API key work perfectly. But those modules don't.
  
It seems that the modules check for key validity by requesting the /api/core/v2/apikeys endpoint. This endpoint is an "admin only" endpoint. So the modules can't be used with API key authentication for non-admin users as they need admin access to validate the key.

Can you add the possibility to use those modules with non-admin API key authenticated users ?

Cdlt,
\fab

**Comment by tadeboro** [comment]
Thanks, @kafeinnet, for taking the time to file a bug report.

We were not aware of this API limitation and assumed that the `GET /apikey/my-key-here` would allow us to check the key validity. Unfortunately, I cannot find anything else that we could use to validate the API key.

I asked about this in the Sensu Go Slack channel so maybe someone will suggest an alternative approach to validating API tokens. If nothing comes up, I will simply remove the validation step and let the modules fail a bit later when they realize they do not have access to the resource in question.

Does that sound like a sound plan?

**Comment by kafeinnet** [comment]
I agree that's not a perfect solution but that's OK for me since if the key is invalid or if api key is authentication is not functional the modules will fail anyway.

**Comment by tadeboro** [comment]
@kafeinnet I created a fix for this issue in #196. The fix will be included in the upcoming 1.4.1 release.

**Comment by kafeinnet** [comment]
I pulled the delay-api-key-validation branch on my test environment and I can confirm that this PR fixes my issue. I'll wait the new release for my production environment.

Thanks !

**Comment by tadeboro** [comment]
Just a heads-up: we released a version 1.4.1 of the collection that contains the fixes for this bug.
