### ISSUE TITLE
Centralized authentication

### ISSUE THREAD

**Issue by miha-plesko** [sensu/sensu-go-ansible#21]
Currently each Sensu module performs API authenticatication, which becomes quite redundant in scenario where we invoke multiple Sensu modules in the same play. What we could do is implement connection plugin that would do the following:

1) grab `token` from play vars if present and pass it to module
2) in case `token` was not present in play vars, let module authenticate against Sensu backend. Connection plugin then grabs that token ans stores it as a play variable

This way Sensu modules would be able to reuse token from other Sensu module invocations so they would not need to authenticate everytime.

**Comment by calebhailey** [comment]
Closing due to lack of interest.
