### ISSUE TITLE
Using Sensu Go `devel` version does not work with collection

### ISSUE THREAD

**Issue by WilliamDEdwards** [sensu/sensu-go-ansible#212]
**Bug description**
When using the Sensu Go binary distribution, the version provided is `devel`. The Sensu Go Ansible collection checks for an integer, making it impossible to use.

**How to reproduce the bug**
Use the Ansible Go Ansible collection on a binary distribution Sensu Backend.

**Expected result**
The Ansible Go Ansible collection functions.

**Actual result**
The Ansible Go Ansible collection does not function:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid version number '(devel)'`

**Component versions**
 - Ansible 2.9.12
 - sensu-backend version (devel)+ce, community edition, built with go1.13.1

**Comment by tadeboro** [comment]
It is hard to tell what exactly went wrong using the currently available information. My guess would be that the sensu.sensu_go.user module failed to detect the backend version. But to confirm this, I will need a stack trace from the error, together with a task invocation that triggers the exception.

**Comment by WilliamDEdwards** [comment]
Hi,

Task:

```
- name: Create sensu user
  sensu.sensu_go.user:
    auth:
      url: "https://{{ item.host }}:8080"
      password: "{{ hostvars[item.host].sensu_admin_password }}"
    name: "{{ inventory_hostname }}"
    password: "{{ sensu_agent_password }}"
    groups:
      - system:agents
  delegate_to: "{{ item.host }}"
  with_items: "{{ sensu_backends }}"
```

Output:

```
TASK [Create sensu user] ***********************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid version number '(devel)'
failed: [http-scr02.agr.ha.cyberfusion.cloud -> go0.cyberfusion.cloud] (item={u'ssl': True, u'host': u'go0.cyberfusion.cloud', u'port': 8081}) => {"ansible_loop_var": "item", "changed": false, "item": {"host": "go0.cyberfusion.cloud", "port": 8081, "ssl": true}, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_sensu.sensu_go.user_payload_hb3ici/ansible_sensu.sensu_go.user_payload.zip/ansible_collections/sensu/sensu_go/plugins/modules/user.py\", line 241, in <module>\n    \n  File \"/tmp/ansible_sensu.sensu_go.user_payload_hb3ici/ansible_sensu.sensu_go.user_payload.zip/ansible_collections/sensu/sensu_go/plugins/modules/user.py\", line 211, in main\n    \n  File \"/tmp/ansible_sensu.sensu_go.user_payload_hb3ici/ansible_sensu.sensu_go.user_payload.zip/ansible_collections/sensu/sensu_go/plugins/module_utils/client.py\", line 51, in version\n  File \"/usr/lib/python2.7/distutils/version.py\", line 40, in __init__\n    self.parse(vstring)\n  File \"/usr/lib/python2.7/distutils/version.py\", line 107, in parse\n    raise ValueError, \"invalid version number '%s'\" % vstring\nValueError: invalid version number '(devel)'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by tadeboro** [comment]
Hmm, so the problem here is that the self-compiled version of Sensu Go does not return a valid version number on the `GET /version` request. Instead, it returns `devel`.

We need the version number because Sensu Go broke the user API in the 5.21.0 release. Never versions require that we provide a pre-hashed password while older versions expect a plain-text password.

Maybe you could build your Sensu Go version in a way that contains a version number? I found some instructions in the Sensu Go toplevel readme file at https://github.com/sensu/sensu-go#building-from-source

**Comment by WilliamDEdwards** [comment]
I've temporarily worked around this by manually setting `self._version = '6.0.0'` in `plugins/module_utils/client.py`. Not the best solution, but it'll do for now!

**Comment by WilliamDEdwards** [comment]
I've temporarily worked around this by manually setting `self._version = '6.0.0'` in `plugins/module_utils/client.py`. Not the best solution, but it'll do for now!
