### ISSUE TITLE
Documentation site https://sensu.github.io/sensu-go-ansible/ 404

### ISSUE THREAD

**Issue by andrew-pickin-epi** [sensu/sensu-go-ansible#272]
Reference for this module used to be found at https://sensu.github.io/sensu-go-ansible/
This is no longer available.
If there is an alternative I do not know of it, a redirect would be helpful.

**Comment by tadeboro** [comment]
Hi @andrew-pickin-epi. The location did not change, but it does look like something went wrong with the GitHub pages publishing process when we updated the docs for version 1.9.1 of the collection. I will investigate and report back as soon as possible.

**Comment by tadeboro** [comment]
The documentation site should be back to normal now. @andrew-pickin-epi do things look OK on your side? And thank you again for reporting this.

**Comment by andrew-pickin-epi** [comment]
All looks good again. 
Perhaps you need better monitoring :)
