### ISSUE TITLE
Keeping release process simple yet efficient

### ISSUE THREAD

**Issue by tadeboro** [sensu/sensu-go-ansible#31]
Now that we are starting to release our work to the Ansible Galaxy, it would be time to define how we track those same releases in our git repo.

I would suggest the following convention:

 1. `master` branch contains the latest and greatest in our collection.
 2. `stable` branch points to the most recent tag that we created.

When we create a new collection release, we tag the current `master`'s `HEAD` commit with an appropriate version number and update the `stable` branch.

The main reason for doing this is ensuring that our collection is working as expected without having to test every release we ever made. Under this scenario, we would run daily tests against `master` and `stable` branches.

/cc @miha-plesko @aljazkosir @matejart

**Comment by miha-plesko** [comment]
I agree with your suggestion. It's great that we keep master as target for merging PRs and I also like the fact that there will not be million branches (like one per release or something).

We will only be doing a new branch if we need to backport something to older release, and this is okay.

In short: I vote we go this way

**Comment by matejart** [comment]
👍 

This is a good and clean direction. It suggests that, while `master` is the central place where all the code-checked new features and bug fixes go to, it may not be the source of stable builds, which is OK.

I suppose there will also have to be some branch schema and test frequency for the past releases that are still supported, and as @miha-plesko , this would tie into the process of back-porting, but that's probably a different topic.

**Comment by tadeboro** [comment]
I intentionally kept the initial suggestion as minimalistic as possible. If/when we break the API, we will need to split our history into two separate paths. If we assume that we support versions 1.x and 2.x, we would have a `stable` branch pointing to the latest 2.x tag and, eg. `previous` branch to the latest 1.x tag.

If we need to support more than two versions, we will need to think about our naming a bit more (and about our development practices even more ;).

I will go ahead and create a new `stable` branch. Once @aljazkosir confirms that he agrees to the proposed plan, I will close this issue or adjust the release management based on his input.

**Comment by aljazkosir** [comment]
Sorry for the late response :). I agree with your suggested plan. I haven't worked with git releases that much, but it feels like a right and great approach :+1:  @tadeboro.

**Comment by miha-plesko** [comment]
I think this is now implemented, closing the issue.
