### ISSUE TITLE
1.14.0 not avaialble on Ansible galaxy

### ISSUE THREAD

**Issue by boutetnico** [sensu/sensu-go-ansible#359]
Hey, only up to 1.13.2 is available on https://galaxy.ansible.com/sensu/sensu_go, please publish 1.14.0.

**Comment by juremedvesek** [comment]
Hi. Published to galaxy now. To Automation Hub it will be published in beginning of next week.

**Comment by boutetnico** [comment]
Thanks @juremedvesek!
