### ISSUE TITLE
Update module metadata

### ISSUE THREAD

**Issue by miha-plesko** [sensu/sensu-go-ansible#38]
Before we release 1.0, we need to unify the collection's metadata. We need to make sure all of the modules have this piece of at the top of the file:

```
ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["stableinterface"],
    "supported_by": "certified",
}
```

Also, each `DOCUMENTATION` block must contain `version_added: 1.0` field.

**Comment by tadeboro** [comment]
`supported-by` is not a free-form field: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#ansible-metadata-block

As for the `version_added`, maybe we can use this field to indicate in what version of sensu_go collection this module was added.

**Comment by miha-plesko** [comment]
@tadeboro yeah, sanity tests used to fail regarding `supported_by`, but that appears to have changed - sanity is okay with "XLAB Steampunk"; perhaps they are more open in case of collections. As for `version_added` I'm concerned that you can't tell upfront: currently we have 0.7.0 but what would you put in there - 0.7.1 or 0.8.0 or 1.0.0? :)

**Comment by tadeboro** [comment]
Hmm, I expected that `supported_by` will be set to `certified` in this case, but I must admit I have not checked this with anyone.

As for the version, I would assume that this is set in the commit that prepares repo for release. What is there while the module is `master` branch only is not that important. But again, I am fine just about anything here.

**Comment by tadeboro** [comment]
Before we release 1.0, we need to unify this. I would suggest that we use

```
ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["stableinterface"],
    "supported_by": "XLAB Steampunk",
}
```

and make sure we have `version_added: 1.0` in each `DOCUMENTATION`  block.

@mancabizjak @aljazkosir Does this sound OK to you?

**Comment by tadeboro** [comment]
I adjusted the original proposal based on the feedback I got on IRC:

> 14:01 < tadeboro> What values should we use for our collection modules in ANSIBLE_METADATA block? (Reference docs https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#ansible-metadata-block)
> 14:02 < tadeboro> Are collections bound by the same rules that are mentioned in documentation?
> 14:02 < tadeboro> Or can we place something else in those fields?
> 17:22 <@gundalow> tadeboro: for the moment just do as you would for ansible/ansible
