### ISSUE TITLE
Unable to install collection

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go-ansible#55]
Using the provided command in the readme to install the collection fails:

```
ansible-galaxy collection install sensu.sensu_go -p ~/.ansible/collections
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'
```

I then tried the `--ignore-errors` flag and got around the collector role error, but now have a new one:

```
ansible-galaxy collection install sensu.sensu_go -p ~/.ansible/collections --ignore-errors
 [WARNING]: - sensu.sensu_go was NOT installed successfully: - sorry, sensu.sensu_go was not found on https://galaxy.ansible.com
```

And attempting it locally from a releases download I get even another error:

```
ansible-galaxy collection install /Users/rgeniesse/Downloads/sensu-go-ansible-0.7.2.tar.gz -p ~/.ansible/collections --ignore-errors
 [WARNING]: - /Users/rgeniesse/Downloads/sensu-go-ansible-0.7.2.tar.gz was NOT installed successfully: this role does not appear to have a meta/main.yml file.
```
Using Ansible 2.8.5. Docs for collection usage I referenced:

https://docs.ansible.com/ansible/devel/user_guide/collections_using.html

Seems like collections may not be part of 2.8.5 as `collection` is not a verb:

```
ansible-galaxy --help
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...
```

Please let me know if there is anything else you need.

**Comment by tadeboro** [comment]
Thank you for taking the time and reporting an issue.

Instructions in the readme file assume that we are using Ansible 2.9 or later. Version 2.9 is the first version that supports installing collections using the `ansible-galaxy` command. Unfortunately, Ansible 2.9 is only available as a prerelease. 

For the older version of Ansible, we need to use a separate tool called [mazer][] to install collections.

   [mazer]: https://galaxy.ansible.com/docs/mazer/index.html

We will include this information in the readme file and create a new release as soon as possible.

**Comment by rgeniesse** [comment]
Thanks @tadeboro!

**Comment by miha-plesko** [comment]
Hi @rgeniesse , just a word of warning: docs now mention the mazer tool to install collection on older Ansible 2.8, but our CI/CD doesn't test against anything but Ansible `2.9.0rc1`. So if you want to be on the safe side, go with that.
