### ISSUE TITLE
Add support for secure setup (HTTPS, WSS)

### ISSUE THREAD

**Issue by tadeboro** [sensu/sensu-go-ansible#81]
At the moment, our roles only support setting up a backend that is available over HTTP/WS.

**Comment by mkobel** [comment]
A manual setup with HTTPS/WSS is currently possible:

* Provide the variables `cert-file` and `key-file` as `backend_config` for the backend role.
* Provide a SSL enable `agent_backend_urls` to the agent role.

**Comment by matejart** [comment]
New inventory variables that are detailed in each role's documentation now allow for a managed setup of the HTTPS and WSS.
