### ISSUE TITLE
Agent role isn't useful w/out being able to provision w/ subscriptions

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go-ansible#82]
As part of the agent role, we're not able to provide subscriptions when provisioning an agent. This doesn't make the role too terribly useful. It'd be nice for this role to follow similar conventions that are laid out with the backend role (e.g., like `backend_config`, there should be `agent_config`).

**Comment by matejart** [comment]
Thank you for your post! We have now released version 0.7.6 of the `sensu.sensu_go` collection, which enables the `agent_config` to be used. Please note that the role uses the `backends` group variable information to populate the `/etc/sensu/agent.yml`'s `backend-url` setting to automatically connect agents to the backend.
