### ISSUE TITLE
Improve config file pemissions

### ISSUE THREAD

**Issue by mkobel** [sensu/sensu-go-ansible#95]
The files `/etc/sensu/agent.yml` (agent role, main task) and `/etc/sensu/backend.yml` (backend role, main task) should be readable for sensu only because they can contain credentials (e.g. username/password for API).

With the current default permissions, these files are public readable.

**Comment by tadeboro** [comment]
I am closing this since we merged the fixes @matejart prepared.

**Comment by matejart** [comment]
The roles now create the configuration files owned by `sensu:sensu` and set permissions to `0600`. The change will be effective in the upcoming update of the collection.
